AIRBNB_project:
  outputs:
    dev:
      account: ZYWICWI-OF68525
      database: AIRBNB
      password: HGZH96qxCXudv42
      role:  ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ABHINAV
      warehouse: COMPUTE_WH
  target: dev
